package com.lucas.restgame.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.lucas.restgame.model.BattleStatus;

import java.util.ArrayList;
import java.util.List;

@DynamoDBTable(tableName = "battles")
public class Battle {

    private String battleID;
    private Player player;
    private List<Enemy> enemies;
    private BattleStatus status;
    private int priority;
    private String text;

    // temporary constructors for debug purposes
    public Battle(Player player, Enemy enemy) {
        this.player = player;
        this.enemies = new ArrayList<>();
        this.enemies.add(enemy);
        this.status = BattleStatus.ONGOING;
        this.priority = -1;
        this.text = "";
    }

    public Battle(Player player, List<Enemy> enemies) {
        this.player = player;
        this.enemies = enemies;
        this.status = BattleStatus.ONGOING;
        this.priority = -1;
        this.text = "";
    }

    public Battle() {
        this.player = new Player();
        this.enemies = new ArrayList<>();
        this.enemies.add(new Enemy());
        this.status = BattleStatus.ONGOING;
        this.priority = -1;
        this.text = "";
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getBattleID() {
        return battleID;
    }
    public void setBattleID(String battleID) {
        this.battleID = battleID;
    }

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.M)
    public Player getPlayer() {
        return this.player;
    }
    public void setPlayer(Player player) {
        this.player = player;
    }

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.L)
    public List<Enemy> getEnemies() { return this.enemies; }
    public void setEnemies(List<Enemy> enemies) { this.enemies = enemies; }

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public BattleStatus getStatus() { return this.status; }
    public void setStatus(BattleStatus status) { this.status = status; }

    @DynamoDBAttribute
    public int getPriority() { return this.priority; }
    public void setPriority(int priority) { this.priority = priority; }

    @DynamoDBAttribute
    public String getText() { return this.text; }
    public void setText(String text) { this.text = text; }

    public void resetText() {
        this.text = "";
    }

    public void addText(String text) {
        if (this.text.isEmpty()) {
            this.text = text;
        } else {
            this.text += "/n" + text;
        }
    }

}
