package com.lucas.restgame.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "game")
public class Game {

    private String gameID;
    // TODO replace with Player entity containing health, status, priority
    private int playerHealth;
    private int enemyHealth;
    private int turnNumber;
    private boolean active;

    // temporary constructor for debug purposes
    public Game(int playerHealth, int enemyHealth, int turnNumber, boolean active) {
        this.playerHealth = playerHealth;
        this.enemyHealth = enemyHealth;
        this.turnNumber = turnNumber;
        this.active = active;
    }

    // use default values when creating new Game
    public Game() {
        this.playerHealth = 100;
        this.enemyHealth = 100;
        this.turnNumber = 1;
        this.active = true;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getGameID() {
        return gameID;
    }

    @DynamoDBAttribute
    public int getPlayerHealth() {
        return playerHealth;
    }

    @DynamoDBAttribute
    public int getEnemyHealth() {
        return enemyHealth;
    }

    @DynamoDBAttribute
    public int getTurnNumber() {
        return turnNumber;
    }

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    public boolean isActive() {
        return active;
    }

    public void setGameID(String id) {
        this.gameID = id;
    }

    public void setPlayerHealth(int health) {
        this.playerHealth = health;
    }

    public void setEnemyHealth(int health) {
        this.enemyHealth = health;
    }

    public void setTurnNumber(int number) {
        this.turnNumber = number;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public void incrementTurn() {
        this.turnNumber += 1;
    }
}
